routes/front.php
<?php

use Illuminate\Support\Facades\Route;

Route::redirect('/', 'client/home');
Route::get('change-language/{lang}', 'Controller@changeLanguage')->name('changeLanguage');
Route::get('session-uuid/{uuid}', 'Controller@storeUuidInSession')->name('storeUuidInSession');


Route::group(['middleware' => ['web-lang', 'check-user-type:client'], 'prefix' => 'client', 'namespace' => 'Client', 'as' => 'client.'], function () {

  Route::get('about-us', 'PageController@aboutUs')->name('aboutUs');
  Route::get('contact-us', 'PageController@contactUs')->name('contactUs');
  Route::get('privacy-policy', 'PageController@privacyPolicy')->name('privacyPolicy');
  Route::get('usage-policy', 'PageController@usagePolicy')->name('usagePolicy');
  Route::get('faqs', 'PageController@faqs')->name('faqs');

  Route::get('home', 'HomeController@home')->name('home');
  Route::get('categories', 'HomeController@categories')->name('categories');
  Route::get('filter/{category_id}', 'HomeController@filter')->name('filter');
  Route::get('provider-details/{branch_id}', 'HomeController@providerDetails')->name('providerDetails');

  Route::get('join-greep', 'HomeController@getJoinGreep')->name('getJoinGreep');
  Route::post('join-greep', 'HomeController@storeJoinGreep')->name('storeJoinGreep');

  Route::get('be-greep', 'HomeController@getBeGreep')->name('getBeGreep');
  Route::post('be-greep', 'HomeController@storeBeGreep')->name('storeBeGreep');

  Route::get('be-partner', 'HomeController@getBePartner')->name('getBePartner');
  Route::post('be-partner', 'HomeController@storeBePartner')->name('storeBePartner');

  Route::get('suggestions', 'HomeController@suggestions')->name('suggestions');
  Route::post('suggestions', 'HomeController@storeSuggest')->name('storeSuggest');

  Route::post('sign-up', 'AuthController@register')->name('register');
  Route::post('active-code', 'AuthController@activation')->name('activation');
  Route::post('sign-in', 'AuthController@login')->name('login');
  Route::get('sign-out', 'AuthController@logout')->name('logout');
  Route::post('forget-password', 'AuthController@forgetPassword')->name('forgetPassword');
  Route::post('forget-password-update', 'AuthController@forgetPasswordUpdate')->name('forgetPasswordUpdate');

  // todo: move under middleware
  Route::get('prev-orders', 'UserController@prevOrders')->name('prevOrders');
  Route::get('favourite', 'UserController@favourite')->name('favourite');
  Route::get('wallet', 'UserController@wallet')->name('wallet');
  Route::get('create-payment-card', 'UserController@createPaymentCard')->name('createPaymentCard');
  Route::group(['middleware' => 'auth'], function () {
    Route::get('order-summary', 'UserController@orderSummary')->name('orderSummary');
    Route::post('profile', 'AuthController@profile')->name('profile');
  });

});

Route::group(['prefix' => 'adminLangPage', 'namespace' => 'FrontAdmin', 'as' => 'adminFront.'], function () {

  Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index')->name('index');
    Route::resource('users', 'UserController');
    Route::resource('contents', 'contentController');
    Route::resource('sliders', 'sliderController');
    Route::resource('reviews', 'reviewController');
    Route::resource('statements', 'statementController');
    Route::resource('fqs', 'fqsController');
    Route::resource('blogs', 'blogController');
    Route::resource('contactDetails', 'contactDetailsController');
    Route::resource('aboutUs', 'aboutUsController');
    Route::resource('aboutStatements', 'aboutStatementController');
  });

  Route::post('/logout', 'DashboardController@logout')->name('logout');
  Route::get('/login', 'DashboardController@showLoginForm')->name('login');
  Route::post('/login', 'DashboardController@login')->name('post.login');
  Route::get('/home', 'HomeController@index')->name('home');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route::get('qr-code-g', function () {
//    \SimpleSoftwareIO\QrCode\Facades\QrCode::size(500)
//        ->format('png')
//        ->generate('ItSolutionStuff.com', public_path('images/qrcode.png');
//
//    return view('qrCode');
//
//});
Route::get('clear', function () {
  return \Illuminate\Support\Facades\Artisan::call('migrate');
});


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
  Route::get('lang/{lang}', function ($lang) {
    Session::put('applocale', $lang);
    return redirect()->back();
  })->name('change.lang');
  //    Route::get('theme/{theme}', function ($theme){
  //        Session::put('theme', $theme);
  //        return redirect()->back();
  //    })->name('change.theme');

  Route::get('them/{them}', 'HomeController@them')->name('them');
  Route::get('login', [
    'uses'  => 'AuthController@showLoginForm',
    'title' => 'تسجيل الدخول',
  ])->name('show.login');
  Route::post('login', 'AuthController@login')->name('login');
  Route::post('logout', 'AuthController@logout')->name('logout');
  Route::get('change-language/{lang}', 'HomeController@changeLanguage')->name('change.language');

  Route::group(['middleware' => ['admin', 'check-role', 'admin-lang']], function () {

    /********************************* HomeController start *********************************/
    Route::get('dashboard', [
      'uses'  => 'HomeController@dashboard',
      'as'    => 'dashboard',
      'icon'  => '<i class="feather icon-home"></i>',
      'title' => 'الرئيسيه',
      'type'  => 'parent'
    ]);
    /********************************* HomeController end *********************************/
    /********************************* StatisticsController start *********************************/

      #statistics routes
    Route::get('statistics', [
      'as'        => 'admin.statistics',
      'title'     => 'الاحصائيات',
      'icon'      => '<i class="feather icon-pie-chart"></i>',
      'type'      => 'parent',
      'sub_route' => true,
      'child'     => ['statistics.sales','statistics.providers']
    ]);

    Route::get('statistics/sales', ['uses' => 'StatisticsController@sales', 'as' => 'statistics.sales', 'title' => 'المبيعات والخدمات', 'icon' => '<i class="nav-icon fa fa-list"></i>']);
    Route::get('statistics/providers', ['uses' => 'StatisticsController@providers', 'as' => 'statistics.providers', 'title' => 'مبيعات مقدمي الخدمه', 'icon' => '<i class="nav-icon fa fa-list"></i>']);
//    Route::get('statistics/clients', ['uses' => 'StatisticsController@clients', 'as' => 'statistics.clients', 'title' => 'المستخدمين', 'icon' => '<i class="nav-icon fa fa-list"></i>']);
////    Route::get('statistics/visits', ['uses' => 'StatisticsController@visits', 'as' => 'statistics.visits', 'title' => 'الزيارات', 'icon' => '<i class="nav-icon fa fa-list"></i>']);
//    Route::get('statistics/almostorder', ['uses' => 'StatisticsController@almostOrder', 'as' => 'statistics.almostOrder', 'title' => 'الأكثر طلبا', 'icon' => '<i class="nav-icon fa fa-list"></i>']);
//    Route::get('statistics/delegates', ['uses' => 'StatisticsController@delegates', 'as' => 'statistics.delegates', 'title' => 'السائقين', 'icon' => '<i class="nav-icon fa fa-list"></i>']);
//    Route::post('statistics/getdata', ['uses' => 'StatisticsController@getdata', 'as' => 'statistics.getdata', 'title' => 'جلب البيانات']);
    /********************************* RoleController start *********************************/
    Route::get('roles', [
      'uses'      => 'RoleController@index',
      'as'        => 'roles.index',
      'title'     => 'قائمة الصلاحيات',
      'icon'      => '<i class="feather icon-user-check"></i>',
      'type'      => 'parent',
      'sub_route' => false,
      'child'     => ['roles.create', 'roles.store', 'roles.edit', 'roles.update', 'roles.delete']
    ]);

    Route::get('roles/create', ['uses' => 'RoleController@create', 'as' => 'roles.create', 'title' => 'اضافة صلاحيه']);
    Route::post('roles/store', ['uses' => 'RoleController@store', 'as' => 'roles.store', 'title' => 'تمكين اضافة صلاحيه']);
    Route::get('roles/{id}/edit', ['uses' => 'RoleController@edit', 'as' => 'roles.edit', 'title' => 'تعديل صلاحيه']);
    Route::put('roles/{id}', ['uses' => 'RoleController@update', 'as' => 'roles.update', 'title' => 'تمكين تعديل صلاحيه']);
    Route::delete('roles/{id}', ['uses' => 'RoleController@destroy', 'as' => 'roles.delete', 'title' => 'حذف صلاحيه']);
    /********************************* RoleController end *********************************/

    /********************************* SettingController , SocialController  start *********************************/


    Route::get('settings', ['uses' => 'SettingController@index', 'as' => 'settings.index', 'title' => 'الاعدادات', 'icon' => '<i class="nav-icon fa fa-cog"></i>']);
    Route::post('settings', ['uses' => 'SettingController@update', 'as' => 'settings.update', 'title' => 'تحديث الاعدادات']);
    Route::post('socials/store', ['uses' => 'SocialController@store', 'as' => 'socials.store', 'title' => 'اضافه وسائل التواصل']);
    Route::post('socials', ['uses' => 'SocialController@update', 'as' => 'socials.update', 'title' => 'تحديث وسائل التواصل']);
    /********************************* SettingController , SocialController end *********************************/

    /********************************* CarTypeController start *********************************/
    Route::get('general', [
      'as'        => 'general',
      'icon'      => '<i class="fa fa-globe"></i>',
      'title'     => 'الاعدادت الرئيسيه',
      'type'      => 'parent',
      'sub_route' => true,
      'child'     => [
        'settings.index', 'settings.update', 'socials.store', 'socials.update',
        'carTypes.index', 'carTypes.store', 'carTypes.update', 'carTypes.destroy',
        'discountAmount.index', 'discountAmount.store', 'discountAmount.update', 'discountAmount.destroy',
        'types.index', 'types.store', 'types.update', 'types.destroy',
        'ratingList.index', 'ratingList.store', 'ratingList.update', 'ratingList.destroy',
        'countryCodes.index', 'countryCodes.update',
      ]
    ]);
    Route::get('car_types', ['uses' => 'CarTypeController@index', 'as' => 'carTypes.index', 'title' => 'أنواع السيارات', 'icon' => '<i class="nav-icon fa fa-globe"></i>']);
    Route::post('carTypes/store', ['uses' => 'CarTypeController@store', 'as' => 'carTypes.store', 'title' => 'اضافة نوع سياره']);
    Route::post('carTypes/{id}', ['uses' => 'CarTypeController@update', 'as' => 'carTypes.update', 'title' => 'تعديل نوع سياره']);
    Route::delete('carTypes/{id}', ['uses' => 'CarTypeController@destroy', 'as' => 'carTypes.destroy', 'title' => 'حذف نوع سياره']);


    Route::get('discountAmount', ['uses' => 'DiscountAmountController@index', 'as' => 'discountAmount.index', 'title' => 'أسباب الخصم', 'icon' => '<i class="nav-icon fa fa-globe"></i>']);
    Route::post('discountAmount/store', ['uses' => 'DiscountAmountController@store', 'as' => 'discountAmount.store', 'title' => 'اضافة سبب خصم']);
    Route::post('discountAmount/{id}', ['uses' => 'DiscountAmountController@update', 'as' => 'discountAmount.update', 'title' => 'تعديل سبب خصم']);
    Route::delete('discountAmount/{id}', ['uses' => 'DiscountAmountController@destroy', 'as' => 'discountAmount.destroy', 'title' => 'حذف سبب خصم']);


    Route::get('types', ['uses' => 'TypeController@index', 'as' => 'types.index', 'title' => 'السمات الأساسيه للمنتج', 'icon' => '<i class="nav-icon fa fa-tag"></i>']);
    Route::post('types/store', ['uses' => 'TypeController@store', 'as' => 'types.store', 'title' => 'اضافة سمه للمنتجات']);
    Route::post('types/{id}', ['uses' => 'TypeController@update', 'as' => 'types.update', 'title' => 'تعديل سمه للمنتجات']);
    Route::delete('types/{id}', ['uses' => 'TypeController@destroy', 'as' => 'types.destroy', 'title' => 'حذف سمه للمنتجات']);
    /********************************* CarTypeController end *********************************/

    Route::get('ratingList', ['uses' => 'RatingListController@index', 'as' => 'ratingList.index', 'title' => 'قائمة التقييمات الاساسيه', 'icon' => '<i class="nav-icon fa fa-tag"></i>']);
    Route::post('ratingList/store', ['uses' => 'RatingListController@store', 'as' => 'ratingList.store', 'title' => 'اضافة مسمي تقييم']);
    Route::post('ratingList/{id}', ['uses' => 'RatingListController@update', 'as' => 'ratingList.update', 'title' => 'تعديل مسمي تقييم']);
    Route::delete('ratingList/{id}', ['uses' => 'RatingListController@destroy', 'as' => 'ratingList.destroy', 'title' => 'حذف مسمي تقييم']);
    /********************************* RatingListController end *********************************/

    Route::get('countryCodes', ['uses' => 'CountryCodesController@index', 'as' => 'countryCodes.index', 'title' => 'أكواد الدول', 'icon' => '<i class="nav-icon fa fa-flag"></i>']);
    Route::post('countryCodes/{id}', ['uses' => 'CountryCodesController@update', 'as' => 'countryCodes.update', 'title' => 'تعديل كود دوله']);
    /********************************* RatingListController end *********************************/
    /********************************* AdminController start *********************************/

      Route::get('admins', [
          'uses'      => 'AdminController@index',
          'as'        => 'admins.index',
          'title'     => 'المشرفين',
          'icon'      => '<i class="feather icon-user"></i>',

resources/views/admin/admins/create.blade.php
@extends('admin.layout.master')
@section('title',__('admin.addAdmin'))
@section('content')

@section('breadcrumb')
    <div style="font-size:14px ; font-family:'cairo' ; color:black">
        <a href="{{ route('admin.admins.index') }}"><span class="user-name"> <i class="feather icon-home"></i> {{__('admin.supervisors')}}</span></a>
        <span class="user-name">/</span>
        <a href="javacsript:void(0)"><span class="user-name">{{__('admin.addAdmin')}}</span></a>
    </div>
@endsection
    <div class="content-body">
        <!-- page users view start -->
        <section class="page-users-view">
            <div class="row">
                <!-- account start -->
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">

                            <form action="{{route('admin.admins.store')}}" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="row">

                                    <div class = "col-sm-12 text-center">
                                        <label class = "mb-0">{{__('avatar')}}</label>
                                        <div class = "text-center">
                                            <div class = "images-upload-block single-image">
                                                <label class = "upload-img">
                                                    <input type = "file" name = "image" id = "image" accept = "image/*" class = "image-uploader">
                                                    <i class="fas fa-cloud-upload-alt"></i>
                                                </label>
                                                <div class = "upload-area" id="upload_area_img"></div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label>{{__('name')}}<span style="color:rgb(145, 4, 4)">*</span></label>
                                            <input type="text" value="{{old('name')}}" name="name" id="name" class="form-control">
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>{{__('phone')}}<span style="color:rgb(145, 4, 4)">*</span></label>
                                            <input type="number" value="{{old('phone')}}" name="phone" class="form-control" id="phone">
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>{{__('email')}}<span style="color:rgb(145, 4, 4)">*</span></label>
                                            <input type="email" value="{{old('email')}}" name="email" class="form-control" id="email">
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>{{__('password')}}<span style="color:rgb(145, 4, 4)">*</span></label>
                                            <input type="password" name="password" class="form-control" autocomplete="off">
                                        </div>
                                    </div>


                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>{{__('role')}}<span style="color:rgb(145, 4, 4)">*</span></label>
                                            <select name="role_id" class="form-control" id="role_id">
                                                <option value="" selected hidden disabled>{{__('choose_role')}}</option>
                                                @foreach($roles as $role)
                                                    <option value="{{$role->id}}" @if(old('role_id') == $role['id']) selected @endif>{{$role->title}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label>{{__('Address')}}</label>
                                            <input type="text" name="address" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>{{__('Country')}}</label>
                                            <select name="country_id" class="form-control" id="country_id">
                                                <option value="" hidden selected>{{__('Choose')}}</option>
                                                @foreach($countries as $country)
                                                    <option value="{{$country['id']}}" @if(old('country_id') == $country['id']) selected @endif>{{$country->title}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>{{__('City')}}</label>
                                            <select name="city_id" class="form-control" id="city_id">
                                                <option value="">{{__('Choose')}}</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary waves-effect waves-light">{{__('save')}}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
@endsection
@push('js')
    {!! JsValidator::formRequest('App\Http\Requests\Admin\Admin\Create') !!}
    <script>
        $(document).on('change','#country_id',function (){
            var country = $(this).val();
            getCities(country);
        });
    </script>
@endpush

resources/views/admin/admins/edit.blade.php
@extends('admin.layout.master')
@section('title',__('admin.ModifyAdmin'))
@section('content')

@section('breadcrumb')
    <div style="font-size:14px ; font-family:'cairo' ; color:black">
        <a href="{{ route('admin.admins.index') }}"><span class="user-name"> <i class="feather icon-home"></i> {{__('admin.supervisors')}}</span></a>
        <span class="user-name">/</span>
        <a href="javacsript:void(0)"><span class="user-name">{{__('admin.ModifyAdmin')}}</span></a>
    </div>
@endsection
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <h2 class="content-header-title float-left mb-0">{{__('admin.supervisors')}}</h2>
                    <div class="breadcrumb-wrapper col-12">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('admin.admins.index') }}">{{__('admin.supervisors')}}</a></li>
                            <li class="breadcrumb-item active">{{__('admin.ModifyAdmin')}}</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <!-- page users view start -->
        <section class="page-users-view">
            <div class="row">
                <!-- account start -->
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">

                            <form action="{{route('admin.admins.update',$admin['id'])}}" id="editForm" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="row">

                                    <div class = "col-sm-12 text-center">
                                        <label class = "mb-0">{{__('avatar')}}</label>
                                        <div class = "text-center">
                                            <div class = "images-upload-block single-image">
                                                <label class = "upload-img">
                                                    <input type = "file" name = "image" id = "image" accept = "image/*" class = "image-uploader">
                                                    <i class="fas fa-cloud-upload-alt"></i>
                                                </label>
                                                <div class = "upload-area" id="upload_area_img">
                                                    <div class="uploaded-block" data-count-order="0">
                                                        <a href="{{$admin['avatar']}}" data-fancybox="" data-caption="{{$admin['avatar']}}">
                                                            <img src="{{$admin['avatar']}}">
                                                        </a>
                                                        <button class="close" type="button">×</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label>{{__('name')}}<span style="color:rgb(145, 4, 4)">*</span></label>
                                            <input type="text" value="{{$admin['name']}}" name="name" id="name" class="form-control">
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>{{__('phone')}}<span style="color:rgb(145, 4, 4)">*</span></label>
                                            <input type="number" value="{{$admin['phone']}}" name="phone" class="form-control" id="phone">
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>{{__('email')}}<span style="color:rgb(145, 4, 4)">*</span></label>
                                            <input type="email" value="{{$admin['email']}}" name="email" class="form-control" id="email">
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>{{__('password')}}<span style="color:rgb(145, 4, 4)">*</span></label>
                                            <input type="password" name="password" class="form-control" autocomplete="off">
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>{{__('role')}}<span style="color:rgb(145, 4, 4)">*</span></label>
                                            <select name="role_id" class="form-control" id="role_id">
                                                <option value="" selected hidden disabled>{{__('choose_role')}}</option>
                                                @foreach($roles as $role)
                                                    <option value="{{$role->id}}" @if($admin['role_id'] == $role['id']) selected @endif>{{$role->title}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label>{{__('Address')}}</label>
                                            <input type="text" name="address" value="{{$admin['address']}}" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>{{__('Country')}}</label>
                                            <select name="country_id" class="form-control" id="country_id">
                                                <option value="" hidden selected>{{__('Choose')}}</option>
                                                @foreach($countries as $country)
                                                    <option value="{{$country['id']}}" @if($admin['country_id'] == $country['id']) selected @endif>{{$country->title}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>{{__('City')}}</label>
                                            <select name="city_id" class="form-control" id="city_id">
                                                <option value="">{{__('Choose')}}</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary waves-effect waves-light">{{__('save')}}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
@endsection
@push('js')
    {!! $validator->selector('#editForm') !!}
    <script>
        getCities(`{{$admin['country_id']}}`,`{{$admin['city_id']}}`);
        $(document).on('change','#country_id',function (){
            var country = $(this).val();
            getCities(country);
        });
    </script>
@endpush